### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by hello2mao** [decentralized-identity/ion#43]
I got this error when run `npm run build`.

```shell
$ npm i  
up to date in 4.788s
$ npm run build

> ion@0.4.1 build /Users/maohongbin01/github.com/decentralized-identity/ion
> tsc && copyfiles "json/**/*.json" dist && copyfiles "tests/**/*.json" dist

src/bitcoin.ts:76:50 - error TS2339: Property 'getServiceVersion' does not exist on type 'BitcoinProcessor'.

76   const requestHandler = () => blockchainService.getServiceVersion();
                                                    ~~~~~~~~~~~~~~~~~

src/core.ts:37:39 - error TS2551: Property 'handleGetVersionRequest' does not exist on type 'Core'. Did you mean 'handleOperationRequest'?

37   const response = await sidetreeCore.handleGetVersionRequest();
                                         ~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@decentralized-identity/sidetree/dist/lib/core/Core.d.ts:31:5
    31     handleOperationRequest(request: Buffer): Promise<ResponseModel>;
           ~~~~~~~~~~~~~~~~~~~~~~
    'handleOperationRequest' is declared here.

src/ipfs.ts:30:41 - error TS2339: Property 'handleGetVersionRequest' does not exist on type 'RequestHandler'.

30   const response = await requestHandler.handleGetVersionRequest();
                                           ~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ion@0.4.1 build: `tsc && copyfiles "json/**/*.json" dist && copyfiles "tests/**/*.json" dist`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ion@0.4.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maohongbin01/.npm/_logs/2019-09-29T06_35_33_987Z-debug.log
```

Additional Info:
```shell
$ node -v
v12.9.1
$ npm -v
6.10.2
```

**Comment by hello2mao** [comment]
Same error with node v10.16.3 ^_^.

**Comment by DrNeil** [comment]
I got the same issue. Build works with latest release v0.4.1, from here [https://github.com/decentralized-identity/ion/releases/tag/v0.4.1](https://github.com/decentralized-identity/ion/releases/tag/v0.4.1)

**Comment by adambarlow** [comment]
@thehenrytsai I am hitting the same issue here on 0.4.1. Any suggestions on what to check first?

@DrNeil did you change anything except upgrading to 0.4.1? What are the version numbers of node and npm for you?

**Comment by DrNeil** [comment]
@adambarlow 

Node.js 10.16.3 (x64)
npm 6.9.0

**Comment by thehenrytsai** [comment]
@adambarlow is right, syncing to release v0.4.1 will fix the build issue, but we do recognize the issue here:

The reason why the latest master branch doesn't build is because the recent commits after the v0.4.1 release require the latest changes in the Sidetree repo itself, which don't exist in the v0.4.1.

So to address this, I will immediately create a `dev` branch and going forward development will occur there, so the master branch remains pristine in release condition.

I will also publish v0.5.0 release now to fix the master branch build issue.

**Comment by DrNeil** [comment]
@thehenrytsai  thanks - I would recommend using a process (such as GitFlow) that means the master can always build

**Comment by adambarlow** [comment]
@thehenrytsai thanks. I'll try and build the new master and see how it goes.

**Comment by thehenrytsai** [comment]
Closing this bug now @adambarlow has confirmed in #46 that this issue is now fixed.
